name: Deploy with tar

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: composer run-script test

      - name: Tar files
        run: tar -cvf artifact.tar *

      - name: Rsync to server
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: artifact.tar
          remote_path: /tmp/tekerrr-artifact.tar
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Extract artifact on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /tmp
            rm -rf ${{ secrets.SSH_PATH_TO_FOLDER }}/*
            tar xf tekerrr-artifact.tar --directory=${{ secrets.SSH_PATH_TO_FOLDER }}
            rm tekerrr-artifact.tar
